name: couple_calendar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  kakao_flutter_sdk: ^1.9.7+3
  lazy_load_scrollview: ^1.3.0
  logger: ^2.5.0
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^12.0.0+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2
  sign_in_with_apple: ^6.1.4
  tuple: ^2.0.2
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5
  package_info_plus: ^8.3.0
  dartx: ^1.2.0
  flutter_switch: ^0.3.2
  numberpicker: ^2.1.2
  carousel_slider: ^5.0.0
  fl_chart: ^0.70.2
  smooth_page_indicator: ^1.2.1
  flutter_inset_shadow: ^2.0.3
  provider: ^6.1.2
  ntp: ^2.0.0
  uuid: ^4.5.1
  kpostal: ^1.1.0
  dio: ^5.8.0+1
  animated_bottom_navigation_bar: ^1.4.0
  event_bus: ^2.0.1
  back_button_interceptor: ^8.0.4
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  easy_localization: ^3.0.7+1
  octo_image: ^2.1.0
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/common/
    - assets/images/common/
    - assets/icons/login/
    - assets/translations/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900
